'use client'

import { useActionState, useState, useRef } from 'react'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Switch } from '@/components/ui/switch'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { criarPonto, editarPonto, type ActionState } from '@/app/actions/pontos'
import { normalizarMunicipio } from '@/lib/pontos/actions'
import type { PontoMidia, TipoPonto, StatusPonto } from '@/types'

// ─── props ───────────────────────────────────────────────────

interface PontoFormProps {
  ponto?: PontoMidia
  codigosExistentes?: string[]
}

// ─── helper ──────────────────────────────────────────────────

function gerarCodigoPreview(municipio: string, codigosExistentes: string[]): string {
  const prefixo = normalizarMunicipio(municipio)
  const doMesmoPrefixo = codigosExistentes.filter(c => c.startsWith(`${prefixo}-`))
  const maxSeq = doMesmoPrefixo.reduce((max, c) => {
    const n = parseInt(c.split('-').pop() ?? '0', 10)
    return n > max ? n : max
  }, 0)
  return `${prefixo}-${String(maxSeq + 1).padStart(3, '0')}`
}

// ─── component ───────────────────────────────────────────────

export function PontoForm({ ponto, codigosExistentes = [] }: PontoFormProps) {
  const isEdit = Boolean(ponto)

  // useActionState expects (state, payload) => result.
  // criarPonto already matches that signature.
  // editarPonto has an extra `id` arg — wrap it to match.
  const action = isEdit
    ? (_prev: ActionState, formData: FormData) => editarPonto(ponto!.id, _prev, formData)
    : criarPonto

  const [state, formAction, pending] = useActionState<ActionState, FormData>(
    action,
    {}
  )

  // ── controlled state ──
  const [tipo, setTipo] = useState<TipoPonto | ''>(ponto?.tipo ?? '')
  const [status, setStatus] = useState<StatusPonto>(ponto?.status ?? 'ativo')
  const [iluminacao, setIluminacao] = useState<boolean>(ponto?.iluminacao ?? false)
  const [codigo, setCodigo] = useState<string>(ponto?.codigo ?? '')
  const [slotDuracao, setSlotDuracao] = useState<string>(
    ponto?.slot_duracao_s ? String(ponto.slot_duracao_s) : ''
  )
  const [fotoPreview, setFotoPreview] = useState<string | null>(
    ponto?.fotos_urls?.[0] ?? null
  )
  const fileRef = useRef<HTMLInputElement>(null)

  // ── helpers ──
  const err = (campo: string) => state.fieldErrors?.[campo]

  function handleMunicipioChange(e: React.ChangeEvent<HTMLInputElement>) {
    const valor = e.target.value
    if (!isEdit && valor.trim().length >= 1) {
      const preview = gerarCodigoPreview(valor, codigosExistentes)
      setCodigo(prev => {
        // só sobrescreve se o campo ainda está com valor gerado automaticamente
        // (ou vazio). Se o usuário editou manualmente, não sobrescreve.
        const prefixo = normalizarMunicipio(valor)
        const isAutoGenerated = prev === '' || /^[A-Z]{3}-\d{3}$/.test(prev)
        return isAutoGenerated ? preview : prev
      })
    }
  }

  function handleFotoChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    if (file.size > 5 * 1024 * 1024) {
      alert('Foto deve ter no máximo 5MB')
      e.target.value = ''
      return
    }
    const url = URL.createObjectURL(file)
    setFotoPreview(url)
  }

  // ── tipo flags ──
  const isOutdoor = tipo === 'outdoor'
  const isFrontlightOrEmpena = tipo === 'frontlight' || tipo === 'empena'
  const isLed = tipo === 'led'
  const hasPainel = isOutdoor || isFrontlightOrEmpena

  return (
    <form action={formAction} className="space-y-8">
      {/* ── erro geral ── */}
      {state.error && (
        <div className="rounded-lg border border-destructive bg-destructive/10 px-4 py-3 text-sm text-destructive">
          {state.error}
        </div>
      )}

      {/* ══ Bloco 1 — Identificação ══ */}
      <section className="space-y-4">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
          Identificação
        </h2>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          {/* Tipo */}
          <div className="space-y-1.5">
            <Label htmlFor="tipo">
              Tipo <span className="text-destructive">*</span>
            </Label>
            <Select
              value={tipo}
              onValueChange={(val) => setTipo(val as TipoPonto)}
              name="tipo"
            >
              <SelectTrigger id="tipo" className="w-full" aria-invalid={Boolean(err('tipo'))}>
                <SelectValue placeholder="Selecione o tipo" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="outdoor">Outdoor</SelectItem>
                <SelectItem value="frontlight">Frontlight</SelectItem>
                <SelectItem value="empena">Empena</SelectItem>
                <SelectItem value="led">LED / DOOH</SelectItem>
              </SelectContent>
            </Select>
            {err('tipo') && <p className="text-xs text-destructive">{err('tipo')}</p>}
          </div>

          {/* Status */}
          <div className="space-y-1.5">
            <Label htmlFor="status">Status</Label>
            <Select
              value={status}
              onValueChange={(val) => setStatus(val as StatusPonto)}
              name="status"
            >
              <SelectTrigger id="status" className="w-full">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="ativo">Ativo</SelectItem>
                <SelectItem value="inativo">Inativo</SelectItem>
                <SelectItem value="manutencao">Em manutenção</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Nome */}
          <div className="space-y-1.5 sm:col-span-2">
            <Label htmlFor="nome">
              Nome Fantasia <span className="text-destructive">*</span>
            </Label>
            <Input
              id="nome"
              name="nome"
              required
              defaultValue={ponto?.nome ?? ''}
              aria-invalid={Boolean(err('nome'))}
              placeholder="Ex: Outdoor Central Park"
            />
            {err('nome') && <p className="text-xs text-destructive">{err('nome')}</p>}
          </div>

          {/* Código */}
          <div className="space-y-1.5">
            <Label htmlFor="codigo">Código</Label>
            <Input
              id="codigo"
              name="codigo"
              value={codigo}
              onChange={(e) => setCodigo(e.target.value)}
              placeholder="Gerado automaticamente"
              aria-invalid={Boolean(err('codigo'))}
            />
            {err('codigo') && <p className="text-xs text-destructive">{err('codigo')}</p>}
          </div>
        </div>
      </section>

      {/* ══ Bloco 2 — Localização ══ */}
      <section className="space-y-4">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
          Localização
        </h2>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          {/* Endereço */}
          <div className="space-y-1.5 sm:col-span-2">
            <Label htmlFor="endereco">
              Endereço <span className="text-destructive">*</span>
            </Label>
            <Input
              id="endereco"
              name="endereco"
              required
              defaultValue={ponto?.endereco ?? ''}
              aria-invalid={Boolean(err('endereco'))}
              placeholder="Av. Brasil, 1000"
            />
            {err('endereco') && <p className="text-xs text-destructive">{err('endereco')}</p>}
          </div>

          {/* Sentido */}
          <div className="space-y-1.5">
            <Label htmlFor="sentido">Sentido</Label>
            <Input
              id="sentido"
              name="sentido"
              defaultValue={ponto?.sentido ?? ''}
              placeholder="ex: sentido RJ"
            />
          </div>

          {/* Bairro */}
          <div className="space-y-1.5">
            <Label htmlFor="bairro">Bairro</Label>
            <Input
              id="bairro"
              name="bairro"
              defaultValue={ponto?.bairro ?? ''}
            />
          </div>

          {/* Município */}
          <div className="space-y-1.5">
            <Label htmlFor="municipio">
              Município <span className="text-destructive">*</span>
            </Label>
            <Input
              id="municipio"
              name="municipio"
              required
              defaultValue={ponto?.municipio ?? ''}
              onChange={handleMunicipioChange}
              aria-invalid={Boolean(err('municipio'))}
            />
            {err('municipio') && <p className="text-xs text-destructive">{err('municipio')}</p>}
          </div>

          {/* Cidade */}
          <div className="space-y-1.5">
            <Label htmlFor="cidade">
              Cidade <span className="text-destructive">*</span>
            </Label>
            <Input
              id="cidade"
              name="cidade"
              required
              defaultValue={ponto?.cidade ?? ''}
              aria-invalid={Boolean(err('cidade'))}
            />
            {err('cidade') && <p className="text-xs text-destructive">{err('cidade')}</p>}
          </div>

          {/* Estado */}
          <div className="space-y-1.5">
            <Label htmlFor="estado">
              Estado <span className="text-destructive">*</span>
            </Label>
            <Input
              id="estado"
              name="estado"
              required
              maxLength={2}
              defaultValue={ponto?.estado ?? ''}
              placeholder="RJ"
              aria-invalid={Boolean(err('estado'))}
              className="uppercase"
            />
            {err('estado') && <p className="text-xs text-destructive">{err('estado')}</p>}
          </div>

          {/* Latitude */}
          <div className="space-y-1.5">
            <Label htmlFor="latitude">Latitude</Label>
            <Input
              id="latitude"
              name="latitude"
              type="number"
              step="any"
              defaultValue={ponto?.latitude ?? ''}
              aria-invalid={Boolean(err('latitude'))}
              placeholder="-22.9068"
            />
            {err('latitude') && <p className="text-xs text-destructive">{err('latitude')}</p>}
          </div>

          {/* Longitude */}
          <div className="space-y-1.5">
            <Label htmlFor="longitude">Longitude</Label>
            <Input
              id="longitude"
              name="longitude"
              type="number"
              step="any"
              defaultValue={ponto?.longitude ?? ''}
              aria-invalid={Boolean(err('longitude'))}
              placeholder="-43.1729"
            />
            {err('longitude') && <p className="text-xs text-destructive">{err('longitude')}</p>}
          </div>
        </div>
      </section>

      {/* ══ Bloco 3 — Características ══ */}
      <section className="space-y-4">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
          Características
        </h2>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          {/* Largura */}
          <div className="space-y-1.5">
            <Label htmlFor="largura_m">Largura (m)</Label>
            <Input
              id="largura_m"
              name="largura_m"
              type="number"
              step="any"
              min="0"
              defaultValue={ponto?.largura_m ?? ''}
              placeholder="9.0"
            />
          </div>

          {/* Altura */}
          <div className="space-y-1.5">
            <Label htmlFor="altura_m">Altura (m)</Label>
            <Input
              id="altura_m"
              name="altura_m"
              type="number"
              step="any"
              min="0"
              defaultValue={ponto?.altura_m ?? ''}
              placeholder="3.0"
            />
          </div>

          {/* Iluminação */}
          <div className="flex items-center gap-3 sm:col-span-2">
            <Label htmlFor="switch-iluminacao">Iluminação</Label>
            <input type="hidden" name="iluminacao" value={iluminacao ? 'true' : 'false'} />
            <Switch
              id="switch-iluminacao"
              checked={iluminacao}
              onCheckedChange={setIluminacao}
            />
            <span className="text-sm text-muted-foreground">
              {iluminacao ? 'Sim' : 'Não'}
            </span>
          </div>

          {/* Nº Painel — Outdoor (Tabuleta) */}
          {isOutdoor && (
            <div className="space-y-1.5">
              <Label htmlFor="numero_painel">Tabuleta Nº</Label>
              <Input
                id="numero_painel"
                name="numero_painel"
                type="number"
                min={1}
                defaultValue={ponto?.numero_painel ?? 1}
              />
            </div>
          )}

          {/* Nº Painel — Frontlight / Empena */}
          {isFrontlightOrEmpena && (
            <div className="space-y-1.5">
              <Label htmlFor="numero_painel">Painel Nº</Label>
              <Input
                id="numero_painel"
                name="numero_painel"
                type="number"
                min={1}
                defaultValue={ponto?.numero_painel ?? 1}
              />
            </div>
          )}

          {/* LED — campos específicos */}
          {isLed && (
            <>
              <div className="space-y-1.5">
                <Label htmlFor="slots_totais">
                  Cotas totais <span className="text-destructive">*</span>
                </Label>
                <Input
                  id="slots_totais"
                  name="slots_totais"
                  type="number"
                  min={1}
                  required
                  defaultValue={ponto?.slots_totais ?? ''}
                  aria-invalid={Boolean(err('slots_totais'))}
                />
                {err('slots_totais') && (
                  <p className="text-xs text-destructive">{err('slots_totais')}</p>
                )}
              </div>

              <div className="space-y-1.5">
                <Label htmlFor="slot_duracao_s">
                  Duração da cota <span className="text-destructive">*</span>
                </Label>
                <Select
                  value={slotDuracao}
                  onValueChange={(val) => setSlotDuracao(val ?? '')}
                  name="slot_duracao_s"
                >
                  <SelectTrigger
                    id="slot_duracao_s"
                    className="w-full"
                    aria-invalid={Boolean(err('slot_duracao_s'))}
                  >
                    <SelectValue placeholder="Selecione a duração" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="10">10 segundos</SelectItem>
                    <SelectItem value="15">15 segundos</SelectItem>
                  </SelectContent>
                </Select>
                {err('slot_duracao_s') && (
                  <p className="text-xs text-destructive">{err('slot_duracao_s')}</p>
                )}
              </div>

              <div className="space-y-1.5 sm:col-span-2">
                <Label htmlFor="resolucao">Resolução</Label>
                <Input
                  id="resolucao"
                  name="resolucao"
                  defaultValue={ponto?.resolucao ?? ''}
                  placeholder="ex: 1920x1080"
                />
              </div>
            </>
          )}
        </div>
      </section>

      {/* ══ Bloco 4 — Foto ══ */}
      <section className="space-y-4">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
          Foto
        </h2>

        <div className="space-y-3">
          {fotoPreview && (
            <div className="overflow-hidden rounded-lg border border-border">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={fotoPreview}
                alt="Preview da foto do ponto"
                className="max-h-64 w-full object-cover"
              />
            </div>
          )}
          <div className="space-y-1.5">
            <Label htmlFor="foto">
              {fotoPreview ? 'Substituir foto' : 'Foto do ponto'}
            </Label>
            <Input
              ref={fileRef}
              id="foto"
              name="foto"
              type="file"
              accept="image/jpeg,image/png"
              onChange={handleFotoChange}
              className="cursor-pointer"
            />
            <p className="text-xs text-muted-foreground">JPEG ou PNG, máximo 5MB</p>
          </div>
        </div>
      </section>

      {/* ══ Bloco 5 — Observações ══ */}
      <section className="space-y-4">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
          Observações
        </h2>
        <Textarea
          id="observacoes"
          name="observacoes"
          defaultValue={ponto?.observacoes ?? ''}
          placeholder="Informações adicionais sobre o ponto..."
          rows={4}
        />
      </section>

      {/* ── Ações ── */}
      <div className="flex items-center gap-3 pt-2">
        <Button type="submit" disabled={pending}>
          {pending ? 'Salvando…' : isEdit ? 'Salvar alterações' : 'Criar ponto'}
        </Button>
        <Button
          type="button"
          variant="outline"
          onClick={() => window.history.back()}
        >
          Cancelar
        </Button>
      </div>
    </form>
  )
}
